query crescoAdminGetAdminList{
    crescoAdminGetAdminList{
        displayName
        email
        emails
        passwordHash
        phone
        phones
        roles
        rolesJwt
        scope
        telegramId
        telegramIds
    }
}