query crescoCustomerGetMyProfile{
    crescoCustomerGetMyProfile{
        agreement{
            fileUrl{
                name
                url
            }
            isPrepared
            isSignedByClient
            no
        }
        crescoTokenBalance
        deposit{
            depositNo
            finishDate
            percentRate
            startDate
        }
        firstName
        isPassportVerified
        lastName
        middleName
        passportScanFiles{
            name
            url
        }
        userUri
        walletAddress
    }
}