query crescoCustomerTransactionList{
    crescoCustomerTransactionList{
        _id
        amountCrescoTokens
        amountUSDT
        fromWallet
        status
        toWallet
        transactionType
        userUri
    }
}