query getUpcomingSevaPremEvents{
    getUpcomingSevaPremEvents{
        _id
        city
        dateTimeEnd
        dateTimeStart
        eduProductEvent{
            abstract
            disclaimers{
                description
                title
            }
            eventDescriptor
            eventName
            faq{
                answer{
                    description
                    title{
                        description
                    }
                }
                comment
                question{
                    description
                    title
                }
            }
            groupLeaders{
                bio
                displayName
                instagramLink
                telegramChannelLink
            }
            portraits{
                description
                displayName
                internalName
            }
            priceConditions{
                prepayBaseRub
                priceBaseRub
            }
            priceConditionsText
            productFeatures{
                description
                portraitsPov{
                    portrait{
                        description
                        displayName
                        internalName
                    }
                    rating
                }
                rating
                title
            }
            reasonsToAttend{
                description
                portraitsPov{
                    rating
                }
                rating
                title
            }
            reasonsToAttendTitle
            uvpSubtitle
            uvpTitle
        }
        faqInstance{
            answer{
                description
            }
            comment
            question{
                description
                title
            }
        }
        groupLeaders{
            bio
            displayName
            instagramLink
            telegramChannelLink
        }
        placement{
            faqInstance{
                comment
            }
            isOffline
            isOnline
            managerContacts{
                displayName
            }
            offlineRoom{
                addressShort
                city
                howToReach
            }
            onlineRooms{
                attendLink
            }
        }
        priceConditionsText
    }
}