export const fieldsets = {
 
fieldsetCrescoCustomer: [{name:'firstName',isRequired:true,title:'Name',fieldType:'String',aclArgs:{read:['all'],write:['all']}},{name:'middleName',isRequired:true,title:'Middle name',fieldType:'String',aclArgs:{read:['all'],write:['all']}},{name:'lastName',isRequired:true,title:'Last name',fieldType:'String',aclArgs:{read:['all'],write:['all']}},{name:'walletAddress',isRequired:true,title:'USDT Wallet Address (ERC20)',fieldType:'String',aclArgs:{read:['all'],write:['customer']}},{name:'crescoTokenBalance',isRequired:true,title:'Cresco token balance',fieldType:'Float',aclArgs:{read:['all'],write:['admin']}},{name:'passportScanFiles',isRequired:true,title:'Passport scans',fieldType:'FILE_URLS',aclArgs:{read:['all'],write:['all']}},{name:'isPassportVerified',isRequired:true,title:'Profile verified',fieldType:'Boolean',aclArgs:{read:['all'],write:['admin']}},{name:'agreement',isRequired:true,title:'Cresco Agreement',childrenFieldset:{name:'fieldsetCrescoAgreement',isList:false},aclArgs:{read:['all'],write:['admin']}},{name:'deposit',isRequired:true,title:'Cresco deposit',childrenFieldset:{name:'fieldsetCrescoDeposit',isList:true},aclArgs:{read:['all'],write:['admin']}}],
fieldsetCrescoAgreement: [{name:'no',isRequired:true,title:'Agreement #',fieldType:'String'},{name:'fileUrl',isRequired:true,title:'Agreement Link',fieldType:'FILE_URL'},{name:'isPrepared',isRequired:true,title:'Agreement Signed?',fieldType:'Boolean'}],
fieldsetCrescoDeposit: [{name:'startDate',isRequired:true,title:'Start date',fieldType:'Date'},{name:'finishDate',isRequired:true,title:'Finish date',fieldType:'Date'},{name:'percentRate',isRequired:true,title:'Percent rate',fieldType:'Float'},{name:'depositNo',isRequired:true,title:'Deposit #',fieldType:'String'}],
fieldsetCrescoNotification: [{name:'title',isRequired:true,title:'Title',fieldType:'String'},{name:'text',isRequired:true,title:'Text',fieldType:'String'},{name:'cta',isRequired:true,title:'Call to action text',fieldType:'String'},{name:'ctaUrl',isRequired:true,title:'Call to action link',fieldType:'String'},{name:'emotion',isRequired:true,title:'Emotion',fieldType:'Float'}],

fieldsetMetaforestUserGameFullStatePayload: [{name:'userUri',isRequired:true,title:'User Id',fieldType:'String'},{name:'carrotsBalance',isRequired:true,title:'Баланс морковок',fieldType:'Int'},{name:'activeBunny',isRequired:true,title:'Текущий кролик',childrenFieldset:{name:'fieldsetMetaforestNftInfo',isList:false}},{name:'calculatedBaseParams',isRequired:true,title:'Итоговые характеристики',childrenFieldset:{name:'fieldsetMetaforestBaseParams',isList:false}},{name:'currentJob',isRequired:true,title:'Активное задание',childrenFieldset:{name:'fieldsetMetaforestCurrentJob',isList:false}},{name:'wornInventory',isRequired:true,title:'Активный инвентарь',childrenFieldset:{name:'fieldsetMetaforestNftInfo',isList:true}},{name:'vitalityPercent',isRequired:true,title:'Уровень жизненности игрока',fieldType:'Int'},{name:'energy',isRequired:true,title:'Уровень энергии кролика',fieldType:'Int'},{name:'unopenedLootBoxes',isRequired:true,title:'Лутбоксы',childrenFieldset:{name:'fieldsetLootBox',isList:true}},{name:'unopenedLootBoxesCount',isRequired:true,title:'Количество Доступных лутбоксов',fieldType:'Int'},{name:'carrotsPerLast24Hours',isRequired:true,title:'Морковок, заработаных за последние 24 часа',fieldType:'Float'},{name:'maxCarrotsFor24Hours',isRequired:true,title:'Максимум морковок за 24 часа',fieldType:'Float'},{name:'referralOwn',isRequired:true,title:'Собственная реферальная ссылка',fieldType:'String'},{name:'referral',isRequired:true,title:'Реферальная ссылка',fieldType:'String'},{name:'activeDays',isRequired:true,title:'Дней активности',fieldType:'Int'},{name:'bunnies',isRequired:true,title:'Кролики, доступные пользователю',childrenFieldset:{name:'fieldsetMetaforestNftInfo',isList:true}},{name:'inventory',isRequired:true,title:'Полный инвентарь, доступный пользователю',childrenFieldset:{name:'fieldsetMetaforestNftInfo',isList:true}}],

fieldsetEduProductEvent: [{name:'eventName',isRequired:true,title:'Название события',fieldType:'MARKDOWN_LINE'},{name:'eventDescriptor',isRequired:true,title:'Отображаемый тип события',fieldType:'DICTIONARY',options:['Тренинг']},{name:'groupLeaders',isRequired:true,title:'Ведущий',childrenFieldset:{name:'fieldsetGroupLeader',isList:true}},{name:'uvpTitle',isRequired:true,title:'Заголовок УТП',description:'5-7 слов',fieldType:'MARKDOWN_LINE'},{name:'uvpSubtitle',isRequired:true,title:'Подзаголовок УТП',description:'5-15 слов',fieldType:'MARKDOWN_LINE'},{name:'abstract',isRequired:true,title:'Аннотация',description:'Абзац текста',fieldType:'MARKDOWN'},{name:'reasonsToAttendTitle',isRequired:true,title:'Заголовок тезисов зачем участвовать',description:'Например, Зачем Вам этот тренинг?',fieldType:'MARKDOWN'},{name:'reasonsToAttend',isRequired:true,title:'Тезисы - зачем участвовать?',childrenFieldset:{name:'fieldsetReasonToAttend',isList:true}},{name:'productFeatures',isRequired:true,title:'Особенности продукта',childrenFieldset:{name:'fieldsetProductFeature',isList:true}},{name:'priceConditionsText',isRequired:true,title:'Стоимость участия',fieldType:'MARKDOWN'},{name:'disclaimers',isRequired:true,title:'Дисклеймеры',childrenFieldset:{name:'fieldsetDisclaimer',isList:true}}],
fieldsetEduProductEventInstance: [{name:'eduProductEvent',isRequired:true,title:'Продукт',fieldType:'EXTERNAL_OBJECT',queryResolverName:''},{name:'priceConditionsText',isRequired:true,title:'Стоимость участия',fieldType:'MARKDOWN'}],

fieldsetReasonToAttend: [{name:'title',isRequired:true,title:'Заголовок повода участвовать',fieldType:'MARKDOWN_LINE'},{name:'description',isRequired:true,title:'Подзаголовок повода участвовать',fieldType:'MARKDOWN_LINE'},{name:'rating',isRequired:true,title:'Общий рейтинг тезиса',fieldType:'Float'},{name:'portraitsPov',isRequired:true,title:'Рейтинг тезиса относительно портретов',childrenFieldset:{name:'fieldsetPortraitPov',isList:true}}], 
}