import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {sdk} from "../graphql/sdk";
import Layout from "../components/Layout";
import Dashboard from "../components/screens/Dashboard";
import Equipment from "../components/screens/Equipment";
import {useState} from "react";
import {tabType} from "../components/types/tabType";
import {bunnyInterface} from "../components/interfaces/bunnyInterface";
import {equipmentItem} from "../components/interfaces/equipmentItem";
import {workTask} from "../components/interfaces/workTask";
import {statKeys} from "../components/types/statKeys";
import {activeTask} from "../components/interfaces/activeTask";
import BunnyChange from "../components/screens/BunnyChange";

const Home: NextPage = () => {

    return (
    <div className={'grey-gradient'}>
      <Head>
        <title>Create Next App</title>

          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'font-roboto overscroll-y-none'}>
        {/*<Bunny></Bunny>*/}
          <Layout>
              <BunnyChange/>
          </Layout>
      </main>
    </div>
  )
}

export default Home
