import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {sdk} from "../graphql/sdk";
import Layout from "../components/Layout";
import Dashboard from "../components/screens/Dashboard";
import {useEffect, useState} from "react";
import {tabType} from "../components/types/tabType";
import {bunnyInterface} from "../components/interfaces/bunnyInterface";
import {equipmentItem} from "../components/interfaces/equipmentItem";
import {workTask} from "../components/interfaces/workTask";
import {statKeys} from "../components/types/statKeys";
import {activeTask} from "../components/interfaces/activeTask";
import {AuthConnector} from "../components/auth-connector";


//query_id=AAEvBg0AAAAAAC8GDQCti9A0&user=%7B%22id%22%3A853551%2C%22first_name%22%3A%22Nick%22%2C%22last_name%22%3A%22Erlan%22%2C%22username%22%3A%22nickolaierlan%22%2C%22language_code%22%3A%22en%22%2C%22is_premium%22%3Atrue%7D&auth_date=1660076083&hash=7e75b96b1b650e545333d7053bc3b2826cb250ec5cf37d7a4c03e66538ddfa88
const Home: NextPage = () => {

  return (
    <div className={'grey-gradient'}>

        <AuthConnector/>
      <Head>
        <title>Create Next App</title>

          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'font-roboto overscroll-y-none'}>
        {/*<Bunny></Bunny>*/}
          <Layout>
              <Dashboard></Dashboard>
          </Layout>
      </main>
    </div>
  )
}

export default Home
