 ---
version: "3.8"

services:

  frontend:
    image: "dr.metafora.dev/meta-forest/web-app/frontend/stage:latest"
    labels:
      - "traefik.http.routers.meta-forest-web-app-frontend.rule=Host(`web-app.meta-forest.stage.dev.metafora.dev`)"
      - "traefik.http.routers.meta-forest-web-app-frontend.entrypoints=web,websecure"

      - "traefik.http.routers.meta-forest-web-app-frontend.tls=true"
      - "traefik.http.routers.meta-forest-web-app-frontend.tls.certresolver=http-cert"
      - "traefik.http.routers.meta-forest-web-app-frontend.tls.domains[0].main=meta-forest.stage.dev.metafora.dev"
      - "traefik.http.routers.meta-forest-web-app-frontend.tls.domains[0].sans=web-app.meta-forest.stage.dev.metafora.dev"

    deploy:
      labels:
        - "traefik.http.routers.meta-forest-web-app-frontend.rule=Host(`web-app.meta-forest.stage.dev.metafora.dev`)"
        - "traefik.http.routers.meta-forest-web-app-frontend.entrypoints=web,websecure"

        - "traefik.http.routers.meta-forest-web-app-frontend.tls=true"
        - "traefik.http.routers.meta-forest-web-app-frontend.tls.certresolver=http-cert"
        - "traefik.http.routers.meta-forest-web-app-frontend.tls.domains[0].main=meta-forest.stage.dev.metafora.dev"
        - "traefik.http.routers.meta-forest-web-app-frontend.tls.domains[0].sans=web-app.meta-forest.stage.dev.metafora.dev"

    networks:
      metafora:
        aliases:
          - meta-forest-web-app-frontend

networks:
  metafora:
    external: true
    name: metafora
...
